services:
  traefik:
    image: traefik:v3.6
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reportagent

  backend:
    build: ./backend
    environment:
      - PORT=${BACKEND_PORT}
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/code/app
    networks:
      - reportagent
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=${BACKEND_PORT}"

  frontend:
    build:
      context: ./frontend
      target: dev
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    volumes:
      - ./frontend/src:/code/src
      - ./frontend/index.html:/code/index.html
    networks:
      - reportagent
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"

networks:
  reportagent:
